### ISSUE TITLE
Binary mask and array of int8 ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/ij#1]
Should we store binary mask by playing with bits in a int8 ?

We should make a test case ... on jsperf ... but it is currently broken !

**Comment by targos** [comment]
Not directly related, but I saw a jsperf few days ago that was comparing an array of booleans vs a typed array to store bits. Performance is exactly the same.

**Comment by lpatiny** [comment]
If we create a bit array for binary image for example it is important to find a way to save / load the data.
We will not convert a array of boolean to json !
https://github.com/bramstein/bit-array could be a possibility ?

**Comment by lpatiny** [comment]
https://courses.cs.washington.edu/courses/cse576/book/ch3.pdf

**Comment by lpatiny** [comment]
BINARY images are supported. The best way to set / unset bit are to use the image methods: setbit, setBitXY, clearBit, clearBitXY, toggleBit, toggleBitXY, getBit, getBitXY
