### ISSUE TITLE
top left position

### ISSUE THREAD

**Issue by lpatiny** [image-js/ij#18]
An image may have a top / left optional coordinates.

This will be useful when creating region of interests (ROI) and could also give the possibility to combine backs region or superimpose region on the original image.

Those coordinates would be taken into account when doing operation on a set of images.

**Comment by targos** [comment]
I don't think it is very good to put this kind of information directly in the image. I agree that it is useful and should be returned by the related methods though

**Comment by MariaTrujillo** [comment]
Images have (0,0) coordinates at the top left position since they are
matrixes.
Currently, we are trying to build the median and the gaussian filters using
1D-vector structure for gray-level images.
Diego and Daniel will show us the result tomorrow.

**Comment by lpatiny** [comment]
In the image a parameter "position" has been added. It should be an array containing 2 values [x,y] corresponding to the top left position.
It is already managed in the ROI related functions.
